version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/my_stub_status.conf:/etc/nginx/conf.d/my_stub_status.conf
      - ./util:/util
      - ./logs:/var/log/nginx
      #- ./access.log:/var/log/nginx/access.log
      #- ./error.log:/var/log/nginx/error.log

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=staging.bootladder.com

networks:
  default:
    external:
      name: nginx-proxy
