version: '3.6'

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/my_stub_status.conf:/etc/nginx/conf.d/my_stub_status.conf
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      #- ./conf.d:/etc/nginx/conf.d
      - ./util:/util
      - ./logs:/var/log/nginx
      - ./certs:/etc/nginx/certs/:rw
      - ./certs:/etc/nginx/wtf
      - ./certs:/wtf
      - ./nginx.tmpl:/app/nginx.tmpl
      #- ./access.log:/var/log/nginx/access.log
      #- ./error.log:/var/log/nginx/error.log

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=staging.bootladder.com

networks:
  default:
    external:
      name: nginx-proxy
